package med.voll.api.medico;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import med.voll.api.endereco.Endereco;

@Table(name = "medicos") // this annotation will change the table name to "medicos"
@Entity(name = "Medico") // this annotation will change the entity name to "Medico"
@Getter // this annotation will generate the getters for all the fields
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(of = "id") // this annotation will generate the equals and hashCode methods for the field "id"
public class Medico {

    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String nome;
    private String email;
    private String telefone;
    private String crm;

    @Enumerated(EnumType.STRING)
    private Especialidade especialidade;

    @Embedded
    private Endereco endereco;

    public Medico(MedicoRecord dados) {
        this.nome = dados.nome(); // we are actually getting the "Getter" generated by record, that's why the parameters ().
        this.email = dados.email();
        this.telefone = dados.telefone();
        this.crm = dados.crm();
        this.especialidade = dados.especialidade();
        this.endereco = new Endereco(dados.endereco());
    }
}
